#!/bin/sh

MENUCMD="${MENUCMD:-"menu"}"
TERMCMD="${TERMINAL:-"xterm"}"

term() {
	"$TERMCMD" -e "$@"
}

dialog() {
	term /bin/sh -c '
		printf "\t%s\n" "$@"
		printf "'"$msg"'? [y/N] "
		read arg
		case "$arg" in
		([Yy]*)
			'"$cmd"' "$@" .
			;;
		esac
	' xfilesctl "$@"
}

drop() {
	cmd="$1"
	shift 1
	dialog "$@"
}

notify() {
	term /bin/sh -c '{
		xsel -ob
		echo
	} | {
		set --
		while read f
		do
			case "$f" in
			("")
				;;
			(*)
				noitify-send \"$(printf \"\t%s\n\" \"$f\")\"
				;;
			esac
		done
			;;
		esac
	}'
}

paste() {
	cmd="$1"
	shift 1
	{
		xsel -ob
		echo
	} | {
		set --
		while read f
		do
			case "$f" in
			("")
				;;
			(*)
				set -- "$@" "$f"
				;;
			esac
		done
		dialog "$@"
	}
}

dirmenu() {
	cmd="$1"
	shift 1
	case "$(
	"$MENUCMD" <<-EOF
		copy
		move
		link
		none
	EOF
	)" in
	("copy")
		msg="copy"
		"$cmd" "cp -v" "$@"
		;;
	("move")
		msg="move"
		"$cmd" "mv -v" "$@"
		;;
	("link")
		msg="link"
		"$cmd" "ln -s" "$@"
	esac
}

filemenu() {
	case "$(
	"$MENUCMD" <<-EOF
		open
		rename
		snarf
		trash
		edit
	EOF
	)" in
	("open")
		xdg-open "$@" &

	("rename")
		term vidir "$@"
		;;
	("snarf")
	notify
		# IFS=$(echo -en "\n\b")
	 #  # printf -v var "%s\n" "${@}"
	 #  # IFS=$'\n'; echo "${@}"
		# # notify-send "$c"
		# echo "$@" > ~/filesmenu
	 #  xsel -op | s &
		# # xsel -op | xsel -ib &
		;;
	("trash")
		trash "$@"
		;;
	("edit")
		plumb -e -- "$1"
		;;
	esac
}

cmd="$1"
shift 1
case "$cmd" in
("menu")
	case "$#" in
	(0)
		dirmenu paste "$@"
		;;
	(*)
		xfs "$@"
		# notify
		# echo "$@" | s
		# filemenu "$@"
		;;
	esac
	;;
("drop-ask")
	dirmenu drop "$@"
	;;
("drop-copy")
	msg="copy"
	drop "cp -v" "$@"
	;;
("drop-move")
	msg="move"
	drop "mv -v" "$@"
	;;
("drop-link")
	msg="link"
	drop "ln -s" "$@"
	;;
esac

exit
